version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./orderbook.dockerfile
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "4567:4567"
